from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('china/',views.china, name='china'),
    path('united-arab-emirates/',views.uae, name='uae'),
    path('argentina/',views.argentina, name='argentina'),
    path('austria/',views.austria, name='austria'), 
    path('australia/',views.australia, name='australia'),
    path('belgium/',views.belgium, name='belgium'),   
    path('bulgaria/',views.bulgaria, name='bulgaria'),  
    path('brazil/',views.brazil, name='brazil'),
    path('bulgaria/',views.bulgaria, name='bulgaria'),
    path('canada/',views.canada, name='canada'),
    path('nigeria/',views.nigeria, name='nigeria'),
    path('germany/',views.germany, name='germany'),
    path('ukraine/',views.ukraine, name='ukraine'),
    path('netherlands/',views.netherlands, name='netherlands'),
    path('japan/',views.japan, name='japan'),
    path('egypt/',views.egypt, name='egypt'),
    path('morocco/',views.morocco, name='morocco'),
    path('israel/',views.israel, name='israel'),
    path('south-korea/',views.southkorea, name='southkorea'),
    path('france/',views.france, name='france'),
    path('united-kingdom/',views.uk, name='uk'),
    path('italy/',views.italy, name='italy'),
    path('portugal/',views.portugal, name='portugal'),
    path('south-africa/',views.southafrica, name='southafrica'),
]